Explicitly require `'autoload` for generating `autoloads`
Without this, Emacs 31 fails to apply `make autoloads` with the following error.

	$ make autoloads
	***** MAKING AUTOGENERATED AUTOLOADS  ****
	emacs -batch -q -no-site-file -eval '(setq autoload-package-name "proof" generated-autoload-file "/Users/ianwahbe/.emacs.d/.cache/elpaca/repos/PG/generic/proof-autoloads.el")' -f 	batch-update-autoloads  generic/ lib/ coq/ qrhl/

	Error: void-function (batch-update-autoloads)
	  batch-update-autoloads()
	  command-line-1(("-eval" "(setq autoload-package-name \"proof\" generated-autoload-file \"/Users/ianwahbe/.emacs.d/.cache/elpaca/repos/PG/generic/proof-autoloads.el\")" "-f" "batch-update-autoloads" 	"generic/" "lib/" "coq/" "qrhl/"))
	  command-line()
	  normal-top-level()

	debug-early-backtrace...done
	Symbol’s function definition is void: batch-update-autoloads
	gmake: *** [Makefile.devel:249: autoloads] Error 255